<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE ORDERS02 
[
<!-- Document type Definition per Ordine d'acquisto vs fornitore moduli(OAL) prev cons vs forn. logistico(PRC) -->

<!ELEMENT ORDERS02 (TESTATAMESSAGGIO,TESTATADOCUMENTO,POSIZIONEDOCUMENTO+)>
<!ELEMENT TESTATAMESSAGGIO (MSG_ID,TIPOMESSAGGIO,VERSIONE,DATARIFERIMENTO,ORARIFERIMENTO,SNDPRN,RCVPRN)>
<!ELEMENT MSG_ID (#PCDATA)>
<!ELEMENT TIPOMESSAGGIO (#PCDATA)>
<!ELEMENT VERSIONE (#PCDATA)>
<!ELEMENT DATARIFERIMENTO (#PCDATA)>
<!ELEMENT ORARIFERIMENTO (#PCDATA)>
<!ELEMENT SNDPRN (#PCDATA)>
<!ELEMENT RCVPRN (#PCDATA)>
<!ELEMENT TESTATADOCUMENTO (BELNR,DATUM,ORGID,NAME1,NAME2,STRAS,ORT01,PSTLZ,TELF1,CURCY,ZTERM)>
<!ELEMENT BELNR (#PCDATA)>
<!ELEMENT DATUM (#PCDATA)>
<!ELEMENT ORGID (#PCDATA)>
<!ELEMENT NAME1 (#PCDATA)>
<!ELEMENT NAME2 (#PCDATA)>
<!ELEMENT STRAS (#PCDATA)>
<!ELEMENT ORT01 (#PCDATA)>
<!ELEMENT PSTLZ (#PCDATA)>
<!ELEMENT TELF1 (#PCDATA)>
<!ELEMENT CURCY (#PCDATA)>
<!ELEMENT ZTERM (#PCDATA)>
<!ELEMENT POSIZIONEDOCUMENTO (POSEX,ACTION,IDTNR,WMENG,MENEE,VPREI,ADRN2,WEMPF)>
<!ELEMENT POSEX (#PCDATA)>
<!ELEMENT ACTION (#PCDATA)>
<!ELEMENT IDTNR (#PCDATA)>
<!ELEMENT WMENG (#PCDATA)>
<!ELEMENT MENEE (#PCDATA)>
<!ELEMENT VPREI (#PCDATA)>
<!ELEMENT ADRN2 (#PCDATA)>
<!ELEMENT WEMPF (#PCDATA)>
]>
<ORDERS02>
 <TESTATAMESSAGGIO>
  <MSG_ID>O00022001040000957857</MSG_ID>
  <TIPOMESSAGGIO>OAL</TIPOMESSAGGIO>
  <VERSIONE>1.0</VERSIONE>
  <DATARIFERIMENTO>20050107</DATARIFERIMENTO>
  <ORARIFERIMENTO>114349</ORARIFERIMENTO>
  <SNDPRN>EPI</SNDPRN>
  <RCVPRN>0002200104</RCVPRN>
 </TESTATAMESSAGGIO>
 <TESTATADOCUMENTO>
  <BELNR>6000606770</BELNR>
  <DATUM>20050107</DATUM>
  <ORGID>UR</ORGID>
  <NAME1>FILIALE DI BARI-SEZ.ARRIVI PARTENZE</NAME1>
  <NAME2> </NAME2>
  <STRAS>VIA AMENDOLA 116</STRAS>
  <ORT01>BARI</ORT01>
  <PSTLZ>70100</PSTLZ>
  <TELF1>080 /5507461/5</TELF1>
  <CURCY>EUR</CURCY>
  <ZTERM>1090</ZTERM>
 </TESTATADOCUMENTO>
 <POSIZIONEDOCUMENTO>
   <POSEX>00001</POSEX>
   <ACTION>001</ACTION>
   <IDTNR>W30AA</IDTNR>
   <WMENG>4.000</WMENG>
   <MENEE>CFZ</MENEE>
   <VPREI></VPREI>
   <ADRN2>07PA2/Z20</ADRN2>
   <WEMPF>MALAVENDA</WEMPF>
 </POSIZIONEDOCUMENTO>
 <POSIZIONEDOCUMENTO>
   <POSEX>00001</POSEX>
   <ACTION>001</ACTION>
   <IDTNR>W30AB</IDTNR>
   <WMENG>4.000</WMENG>
   <MENEE>CFZ</MENEE>
   <VPREI></VPREI>
   <ADRN2>07PA2/Z20</ADRN2>
   <WEMPF>MALAVENDA</WEMPF>
 </POSIZIONEDOCUMENTO>
 </ORDERS02>